[build]
  # Build command for Netlify
  command = "npm run build"
  
  publish = "client/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "22.0.0"

[functions]
  directory = "./serverless-functions"
